package hibernate1;
// Generated 04-dic-2019 12:36:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class NuevosDep  implements java.io.Serializable {


     private int deptNo;
     private String dnombre;
     private String loc;
  

    public NuevosDep() {
    }

	
    public NuevosDep(int deptNo) {
        this.deptNo = deptNo;
    }
    public NuevosDep(int deptNo, String dnombre, String loc) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
   
    }
   
    public int getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(int deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }




}


