package hibernate1;
// Generated 04-dic-2019 12:36:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {


     private int nrp;
     private Departamentos departamentos;
     private BigDecimal salario;
     private String nombre;
     private String apellidos;
     private String email;
     private String fechaAlta;

    public Profesores() {
    }

	
    public Profesores(int nrp) {
        this.nrp = nrp;
    }
    public Profesores(int nrp, Departamentos departamentos, BigDecimal salario, String nombre, String apellidos, String email, String fechaAlta) {
       this.nrp = nrp;
       this.departamentos = departamentos;
       this.salario = salario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.fechaAlta = fechaAlta;
    }
   
    public int getNrp() {
        return this.nrp;
    }
    
    public void setNrp(int nrp) {
        this.nrp = nrp;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(String fechaAlta) {
        this.fechaAlta = fechaAlta;
    }




}


